/* eslint-disable linebreak-style */
/* eslint-disable no-unused-vars */
import onlyFans from './onlyfans.png';
import custom from './custom.png';
import instagram from './instagram.png';
import twitter from './twitter.png';
import twitch from './twitch.png';
import youtube from './youtube.png';
import paypal from './paypal.png';
import soundCloud from './soundcloud.png';
import venmo from './venmo.png';
import kofi from './kofi.png';
import patreon from './patreon.png';
import kickStarter from './kickstarter.png';
import discord from './discord.png';
import coffee from './buy_me_a_coffee.png';
import linkTree from './linktree.png';
import reddit from './reddit.png';
import subStack from './substack.png';
import cameo from './cameo.png';
import beacons from './beacons.png';
import tiktok from './tiktok.png';
import facebook from './facebook.png';
import tumblr from './tumblr.png';
import spotify from './spotify.png';
import cashApp from './cash_app.png';
import shopify from './shopify.png';
