version: "3.9"
services:
  frontend:
    container_name: front
    build:
      context: .
      dockerfile: devops.Dockerfile
    networks:
      - proxy-network
    environment:
      - REACT_APP_BASE_URL
    restart: always
    
networks:
  proxy-network:
    external: true
